import type { BotCommand } from "@/bot/commands/types";
import { playCommand, playnextCommand, playtopCommand, playskipCommand } from "@/bot/commands/music/play";
import {
  pauseCommand,
  resumeCommand,
  stopCommand,
  skipCommand,
  previousCommand,
  seekCommand,
  forwardCommand,
  rewindCommand,
  replayCommand,
  joinCommand,
} from "@/bot/commands/music/controls";
import {
  queueCommand,
  nowplayingCommand,
  removeCommand,
  clearCommand,
  moveCommand,
  shuffleCommand,
  skipToCommand,
  removeDuplicatesCommand,
  loopCommand,
  volumeCommand,
} from "@/bot/commands/music/queue";
import {
  searchCommand,
  grabCommand,
  lyricsCommand,
  autoplayCommand,
  stayCommand,
  djModeCommand,
  sleepCommand,
} from "@/bot/commands/music/extras";
import { playlistCommand, favoritesCommand } from "@/bot/commands/playlists/playlist";
import {
  bassboostCommand,
  nightcoreCommand,
  vaporwaveCommand,
  softCommand,
  eightDCommand,
  karaokeCommand,
  tremoloCommand,
  vibratoCommand,
  distortionCommand,
  lowpassCommand,
  speedCommand,
  pitchCommand,
  eqCommand,
  filtersCommand,
  filtersResetCommand,
} from "@/bot/commands/filters";
import {
  settingsCommand,
  prefixCommand,
  languageCommand,
  djRoleCommand,
  botChannelCommand,
  defaultVolumeCommand,
  idleTimeoutCommand,
} from "@/bot/commands/settings";
import {
  helpCommand,
  pingCommand,
  statsCommand,
  inviteCommand,
  aboutCommand,
  nodesCommand,
  developerCommand,
} from "@/bot/commands/info";

export const commandsRegistry: BotCommand[] = [
  // Music
  playCommand,
  playnextCommand,
  playtopCommand,
  playskipCommand,
  pauseCommand,
  resumeCommand,
  stopCommand,
  skipCommand,
  previousCommand,
  seekCommand,
  forwardCommand,
  rewindCommand,
  replayCommand,
  joinCommand,
  queueCommand,
  nowplayingCommand,
  removeCommand,
  clearCommand,
  moveCommand,
  shuffleCommand,
  skipToCommand,
  removeDuplicatesCommand,
  loopCommand,
  volumeCommand,
  searchCommand,
  grabCommand,
  lyricsCommand,
  autoplayCommand,
  stayCommand,
  djModeCommand,
  sleepCommand,
  // Playlists
  playlistCommand,
  favoritesCommand,
  // Filters
  bassboostCommand,
  nightcoreCommand,
  vaporwaveCommand,
  softCommand,
  eightDCommand,
  karaokeCommand,
  tremoloCommand,
  vibratoCommand,
  distortionCommand,
  lowpassCommand,
  speedCommand,
  pitchCommand,
  eqCommand,
  filtersCommand,
  filtersResetCommand,
  // Settings
  settingsCommand,
  prefixCommand,
  languageCommand,
  djRoleCommand,
  botChannelCommand,
  defaultVolumeCommand,
  idleTimeoutCommand,
  // Info
  helpCommand,
  pingCommand,
  statsCommand,
  inviteCommand,
  aboutCommand,
  nodesCommand,
  developerCommand,
];

/** Static catalog lives in src/lib/command-catalog.ts (shared with the web app). */
export { commandCatalog, type CommandCatalogEntry } from "@/lib/command-catalog";
